apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-app
  labels:
    app: user-api-app
spec:
  replicas: 1
  # Property to wait before diverting traffic, to check if instance didnt crash
  minReadySeconds: 10
  selector:
    matchLabels:
      app: user-api-app
  template:
    metadata:
      labels:
        app: user-api-app
    spec:
      containers:
      - name: user-api-app
        image: sdarwant/user-api-app:latest
        ports:
        - containerPort: 4700

