apiVersion: v1
kind: Service
metadata:
 name: merra-api-app
spec:
 type: LoadBalancer
 selector:
    app: merra-api-app
 ports:
  - name: "4800"
    port: 4800
    targetPort: 4800
    nodePort: 30006
