apiVersion: apps/v1
kind: Deployment
metadata:
  name: merra-api-app
  labels:
    app: merra-api-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: merra-api-app
  template:
    metadata:
      labels:
        app: merra-api-app
    spec:
      containers:
      - name: merra-api-app
        image: sdarwant/merra-api-app:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 4800

