apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: weather-cache-app-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-cache-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
